services:
  nginx:
    image: nginx:stable-alpine
    container_name: go-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - internal

  # app:
  #   build: .
  #   container_name: go-api
  #   restart: unless-stopped
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   env_file:
  #     - .env
  #   networks:
  #     - internal

  db:
    image: postgres:16-alpine
    container_name: go-db
    restart: unless-stopped
    ports:
    - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - internal

  redis:
    image: redis:7-alpine
    container_name: go-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - internal

  emailpit:
    image: axllent/mailpit:latest
    container_name: go-emailpit
    restart: unless-stopped
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - internal

  minio:
    image: minio/minio:latest
    container_name: go-minio
    command: server /data --console-address ":9001"
    env_file:
      - .env
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - internal

volumes:
  pgdata:
  minio_data:

networks:
  internal:
    driver: bridge
