// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package db

import (
	"context"
)

const getStats = `-- name: GetStats :one
SELECT
  (SELECT COUNT(*)::int FROM users)  AS users,
  (SELECT COUNT(*)::int FROM heroes) AS heroes,
  (SELECT COUNT(*)::int FROM files)  AS images,
  COALESCE(
    (SELECT SUM((metadata->>'size')::bigint) FROM files),
    0::bigint
)::bigint AS storage_bytes
`

type GetStatsRow struct {
	Users        int32
	Heroes       int32
	Images       int32
	StorageBytes int64
}

func (q *Queries) GetStats(ctx context.Context) (GetStatsRow, error) {
	row := q.db.QueryRow(ctx, getStats)
	var i GetStatsRow
	err := row.Scan(
		&i.Users,
		&i.Heroes,
		&i.Images,
		&i.StorageBytes,
	)
	return i, err
}
