// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: files.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFile = `-- name: CreateFile :exec
INSERT INTO files (
    id,
    path,
    type,
    metadata,
    user_id
) VALUES (
     $1,
     $2,
     $3,
     $4,
     $5
)
`

type CreateFileParams struct {
	ID       pgtype.UUID
	Path     string
	Type     FileType
	Metadata []byte
	UserID   pgtype.UUID
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) error {
	_, err := q.db.Exec(ctx, createFile,
		arg.ID,
		arg.Path,
		arg.Type,
		arg.Metadata,
		arg.UserID,
	)
	return err
}

const deleteFileByPath = `-- name: DeleteFileByPath :exec
DELETE FROM files
WHERE path = $1
`

func (q *Queries) DeleteFileByPath(ctx context.Context, path string) error {
	_, err := q.db.Exec(ctx, deleteFileByPath, path)
	return err
}

const getFileByPath = `-- name: GetFileByPath :one
SELECT id, path, type, metadata, user_id, created_at, updated_at
FROM files
WHERE path = $1 LIMIT 1
`

func (q *Queries) GetFileByPath(ctx context.Context, path string) (File, error) {
	row := q.db.QueryRow(ctx, getFileByPath, path)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.Type,
		&i.Metadata,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
