// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: heroes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createHero = `-- name: CreateHero :exec
INSERT INTO heroes (
    id,
    user_id,
    name,
    slug,
    universe,
    powers,
    alignment,
    description
) VALUES (
     $1,
     $2,
     $3,
     $4,
     $5,
     $6,
     $7,
     $8
    )
`

type CreateHeroParams struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	Name        string
	Slug        string
	Universe    string
	Powers      []string
	Alignment   string
	Description pgtype.Text
}

func (q *Queries) CreateHero(ctx context.Context, arg CreateHeroParams) error {
	_, err := q.db.Exec(ctx, createHero,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Slug,
		arg.Universe,
		arg.Powers,
		arg.Alignment,
		arg.Description,
	)
	return err
}

const getHeroByID = `-- name: GetHeroByID :one
SELECT id, user_id, image
FROM heroes
WHERE id = $1 AND user_id = $2 LIMIT 1
`

type GetHeroByIDParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

type GetHeroByIDRow struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
	Image  pgtype.Text
}

func (q *Queries) GetHeroByID(ctx context.Context, arg GetHeroByIDParams) (GetHeroByIDRow, error) {
	row := q.db.QueryRow(ctx, getHeroByID, arg.ID, arg.UserID)
	var i GetHeroByIDRow
	err := row.Scan(&i.ID, &i.UserID, &i.Image)
	return i, err
}

const getHeroBySlug = `-- name: GetHeroBySlug :one
SELECT id, user_id, name, slug, universe, powers, alignment, description, image, is_active, created_at
FROM heroes
WHERE slug = $1 LIMIT 1
`

type GetHeroBySlugRow struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	Name        string
	Slug        string
	Universe    string
	Powers      []string
	Alignment   string
	Description pgtype.Text
	Image       pgtype.Text
	IsActive    bool
	CreatedAt   pgtype.Timestamp
}

func (q *Queries) GetHeroBySlug(ctx context.Context, slug string) (GetHeroBySlugRow, error) {
	row := q.db.QueryRow(ctx, getHeroBySlug, slug)
	var i GetHeroBySlugRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Slug,
		&i.Universe,
		&i.Powers,
		&i.Alignment,
		&i.Description,
		&i.Image,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listHeroes = `-- name: ListHeroes :many
SELECT id, user_id, name, slug, universe, powers, alignment, description, image, is_active, created_at
FROM heroes
WHERE
    ($1::text IS NULL OR universe = $1)
  AND
    ($2::text IS NULL OR alignment = $2)
  AND
    ($3::boolean IS NULL OR is_active = $3)
ORDER BY created_at DESC
LIMIT $5
OFFSET $4
`

type ListHeroesParams struct {
	Universe   pgtype.Text
	Alignment  pgtype.Text
	IsActive   pgtype.Bool
	PageOffset int32
	PageSize   int32
}

type ListHeroesRow struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	Name        string
	Slug        string
	Universe    string
	Powers      []string
	Alignment   string
	Description pgtype.Text
	Image       pgtype.Text
	IsActive    bool
	CreatedAt   pgtype.Timestamp
}

func (q *Queries) ListHeroes(ctx context.Context, arg ListHeroesParams) ([]ListHeroesRow, error) {
	rows, err := q.db.Query(ctx, listHeroes,
		arg.Universe,
		arg.Alignment,
		arg.IsActive,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHeroesRow
	for rows.Next() {
		var i ListHeroesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Slug,
			&i.Universe,
			&i.Powers,
			&i.Alignment,
			&i.Description,
			&i.Image,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setHeroActiveStatus = `-- name: SetHeroActiveStatus :execrows
UPDATE heroes
SET
    is_active = $3,
    updated_at = now()
WHERE id = $1 AND user_id = $2
`

type SetHeroActiveStatusParams struct {
	ID       pgtype.UUID
	UserID   pgtype.UUID
	IsActive bool
}

func (q *Queries) SetHeroActiveStatus(ctx context.Context, arg SetHeroActiveStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setHeroActiveStatus, arg.ID, arg.UserID, arg.IsActive)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateHero = `-- name: UpdateHero :exec
UPDATE heroes
SET
    name = $3,
    universe = $4,
    powers = $5,
    alignment = $6,
    description = $7,
    updated_at = now()
WHERE id = $1 AND user_id = $2
`

type UpdateHeroParams struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	Name        string
	Universe    string
	Powers      []string
	Alignment   string
	Description pgtype.Text
}

func (q *Queries) UpdateHero(ctx context.Context, arg UpdateHeroParams) error {
	_, err := q.db.Exec(ctx, updateHero,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Universe,
		arg.Powers,
		arg.Alignment,
		arg.Description,
	)
	return err
}

const updateHeroImage = `-- name: UpdateHeroImage :exec
UPDATE heroes
SET image = $3, updated_at = now()
WHERE id = $1 AND user_id = $2
`

type UpdateHeroImageParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
	Image  pgtype.Text
}

func (q *Queries) UpdateHeroImage(ctx context.Context, arg UpdateHeroImageParams) error {
	_, err := q.db.Exec(ctx, updateHeroImage, arg.ID, arg.UserID, arg.Image)
	return err
}
