// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSearchHeroes = `-- name: CountSearchHeroes :one
SELECT COUNT(*) as total
FROM heroes h
WHERE h.search_vector @@ plainto_tsquery('english', $1)
  AND h.is_active = true
  AND (NULLIF($2, '') IS NULL OR h.universe = $2)
  AND (NULLIF($3, '') IS NULL OR h.alignment = $3)
`

type CountSearchHeroesParams struct {
	PlaintoTsquery string
	Column2        interface{}
	Column3        interface{}
}

func (q *Queries) CountSearchHeroes(ctx context.Context, arg CountSearchHeroesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchHeroes, arg.PlaintoTsquery, arg.Column2, arg.Column3)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const searchHeroes = `-- name: SearchHeroes :many
SELECT 
  h.id,
  h.user_id,
  h.name,
  h.slug,
  h.universe,
  h.alignment,
  h.powers,
  h.description,
  h.image,
  h.is_active,
  h.created_at,
  h.updated_at,
  ts_rank(h.search_vector, plainto_tsquery('english', $1)) as rank
FROM heroes h
WHERE h.search_vector @@ plainto_tsquery('english', $1)
  AND h.is_active = true
  AND (NULLIF($2, '') IS NULL OR h.universe = $2)
  AND (NULLIF($3, '') IS NULL OR h.alignment = $3)
ORDER BY rank DESC, h.created_at DESC
LIMIT $4 OFFSET $5
`

type SearchHeroesParams struct {
	PlaintoTsquery string
	Column2        interface{}
	Column3        interface{}
	Limit          int32
	Offset         int32
}

type SearchHeroesRow struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	Name        string
	Slug        string
	Universe    string
	Alignment   string
	Powers      []string
	Description pgtype.Text
	Image       pgtype.Text
	IsActive    bool
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	Rank        float32
}

func (q *Queries) SearchHeroes(ctx context.Context, arg SearchHeroesParams) ([]SearchHeroesRow, error) {
	rows, err := q.db.Query(ctx, searchHeroes,
		arg.PlaintoTsquery,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchHeroesRow
	for rows.Next() {
		var i SearchHeroesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Slug,
			&i.Universe,
			&i.Alignment,
			&i.Powers,
			&i.Description,
			&i.Image,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
